// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgkt8yak5qBJmiAdpzgC0IJFSPbb8WUBo',
    appId: '1:142675395355:web:0a0893b782040e22c189be',
    messagingSenderId: '142675395355',
    projectId: 'food-app-df913',
    authDomain: 'food-app-df913.firebaseapp.com',
    storageBucket: 'food-app-df913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvhr6-WTj_MqH3QqxhF2NPIm1kcLO4AM',
    appId: '1:142675395355:android:d696fc2aace10c7cc189be',
    messagingSenderId: '142675395355',
    projectId: 'food-app-df913',
    storageBucket: 'food-app-df913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB772VZaQJOWI_-dLjGjDGG7nIYLU1zghI',
    appId: '1:142675395355:ios:c73fb8dc12015e48c189be',
    messagingSenderId: '142675395355',
    projectId: 'food-app-df913',
    storageBucket: 'food-app-df913.appspot.com',
    iosClientId: '142675395355-92lutlfbthl993tq4dpnoi4psh2ctvto.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB772VZaQJOWI_-dLjGjDGG7nIYLU1zghI',
    appId: '1:142675395355:ios:c73fb8dc12015e48c189be',
    messagingSenderId: '142675395355',
    projectId: 'food-app-df913',
    storageBucket: 'food-app-df913.appspot.com',
    iosClientId: '142675395355-92lutlfbthl993tq4dpnoi4psh2ctvto.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
